services:
  master:
    image: jenkins/master:latest
    ports:
      - "8080:8080"
    user: root
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./casc_configs:/var/jenkins_home/casc_configs
      - /var/run/docker.sock:/var/run/docker.sock
